[package]
name = "edgeware"
version = "0.1.2"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
build = "build.rs"

[[bin]]
name = "edgeware"
path = "src/main.rs"

[dependencies]
error-chain = "0.12"
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1.7"
exit-future = "0.1"
parking_lot = "0.4"
hex-literal = "0.1"
slog = "^2"
parity-codec = { version = "2.1" }
trie-root = { git = "https://github.com/paritytech/trie" }
sr-io = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-cli = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-executor = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-service = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-network = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-telemetry = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
substrate-client = { git = "https://github.com/paritytech/substrate", branch = "v0.9", default-features = false }
substrate-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
structopt = "0.2.13"
node-executor = { git = "https://github.com/paritytech/substrate", branch = "v0.9" }
edgeware-runtime = { path = "runtime" }

[build-dependencies]
vergen = "2"

[workspace]
members = [
    "primitives",
    "runtime",
    "modules/edge-delegation",
    "modules/edge-governance",
    "modules/edge-identity"
]
exclude = [ "runtime/wasm" ]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
